version: "3.7"
services:
  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"